name: Build
on:
  push:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson==1.4.0 ninja
      - name: Configure Project
        run: meson setup build/ --buildtype release --prefix ${{ github.workspace }}/artifact/ --optimization 3
      - name: Build
        run: ninja -C build install
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ github.workspace }}/artifact
